### ISSUE TITLE
[Question] How to force color for tree output in terminal?

### ISSUE THREAD

**Issue by dman777** [cenfun/monocart-reporter#150]
I really like this plug in for the tree view, it is really helpful and clean. Question, please... how can I make my terminal have color for the tree view? The terminal does show color for the list reporter but not this plugin:

![image](https://github.com/user-attachments/assets/d695a1dc-3fff-4dd5-8ca6-f306aeb60d9f)

**Comment by cenfun** [comment]
try env `FORCE_COLOR=true`
for example Github Actions
```yaml
      - run: npm run test
        env:
          FORCE_COLOR: true
```
